### ISSUE TITLE
PG merge function and nulls: `null value in column "iso_3166_code" violates not-null constraint (PG::Error)`

### ISSUE THREAD

**Issue by seamusabshere** [seamusabshere/upsert#1]
the pg merge function needs to be smarter about nulls where there can't be nulls

```
I, [2012-06-19T11:20:58.262005 #90857]  INFO -- : [data_miner] Country FAILED (5.98s)
/Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/upsert-0.1.2/lib/upsert/buffer/pg_connection.rb:25:in `exec': ERROR:  null value in column "iso_3166_code" violates not-null constraint (PG::Error)
CONTEXT:  SQL statement "UPDATE countries SET iso_3166_code = iso_3166_code_input,iso_3166_numeric_code = iso_3166_numeric_code_input,iso_3166_alpha_3_code = iso_3166_alpha_3_code_input,name = name_input,heating_degree_days = heating_degree_days_input,heating_degree_days_units = heating_degree_days_units_input,cooling_degree_days = cooling_degree_days_input,cooling_degree_days_units = cooling_degree_days_units_input,automobile_urbanity = automobile_urbanity_input,automobile_fuel_efficiency = automobile_fuel_efficiency_input,automobile_fuel_efficiency_units = automobile_fuel_efficiency_units_input,automobile_city_speed = automobile_city_speed_input,automobile_city_speed_units = automobile_city_speed_units_input,automobile_highway_speed = automobile_highway_speed_input,automobile_highway_speed_units = automobile_highway_speed_units_input,automobile_trip_distance = automobile_trip_distance_input,automobile_trip_distance_units = automobile_trip_distance_units_input,electricity_emission_factor = electricity_emission_factor_input,electricity_emission_factor_units = electricity_emission_factor_units_input,electricity_loss_factor = electricity_loss_factor_input,flight_route_inefficiency_factor = flight_route_inefficiency_factor_input,lodging_occupancy_rate = lodging_occupancy_rate_input,lodging_natural_gas_intensity = lodging_natural_gas_intensity_input,lodging_natural_gas_intensity_units = lodging_natural_gas_intensity_units_input,lodging_fuel_oil_intensity = lodging_fuel_oil_intensity_input,lodging_fuel_oil_intensity_units = lodging_fuel_oil_intensity_units_input,lodging_electricity_intensity = lodging_electricity_intensity_input,lodging_electricity_intensity_units = lodging_electricity_intensity_units_input,lodging_district_heat_intensity = lodging_district_heat_intensity_input,lodging_district_heat_intensity_units = lodging_district_heat_intensity_units_input,rail_passengers = rail_passengers_input,rail_trip_distance = rail_trip_distance_input,rail_trip_distance_units = rail_trip_distance_units_input,rail_speed = rail_speed_input,rail_speed_units = rail_speed_units_input,rail_trip_electricity_intensity = rail_trip_electricity_intensity_input,rail_trip_electricity_intensity_units = rail_trip_electricity_intensity_units_input,rail_trip_diesel_intensity = rail_trip_diesel_intensity_input,rail_trip_diesel_intensity_units = rail_trip_diesel_intensity_units_input,rail_trip_co2_emission_factor = rail_trip_co2_emission_factor_input,rail_trip_co2_emission_factor_units = rail_trip_co2_emission_factor_units_input WHERE name = name_input"
PL/pgSQL function "merge_countries_68363704441" line 4 at SQL statement
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/upsert-0.1.2/lib/upsert/buffer/pg_connection.rb:25:in `execute'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/upsert-0.1.2/lib/upsert/buffer.rb:48:in `add'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/upsert-0.1.2/lib/upsert.rb:71:in `row'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/step/import.rb:96:in `block (2 levels) in start'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/remote_table-2.0.1/lib/remote_table.rb:429:in `block (2 levels) in each'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/remote_table-2.0.1/lib/remote_table.rb:418:in `each'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/remote_table-2.0.1/lib/remote_table.rb:418:in `block in each'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/remote_table-2.0.1/lib/remote_table/delimited.rb:66:in `block in _each'
  from /Users/seamusabshere/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/csv.rb:1792:in `each'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/remote_table-2.0.1/lib/remote_table/delimited.rb:35:in `_each'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/remote_table-2.0.1/lib/remote_table.rb:417:in `each'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/step/import.rb:90:in `block in start'
  from /Users/seamusabshere/.rvm/gems/ruby-1.9.3-p194/gems/upsert-0.1.2/lib/upsert.rb:37:in `stream'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/step/import.rb:89:in `start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/script.rb:223:in `block (2 levels) in start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/script.rb:222:in `each'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/script.rb:222:in `block in start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/run.rb:93:in `block in start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/run.rb:92:in `catch'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/run.rb:92:in `start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/script.rb:221:in `start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/active_record_class_methods.rb:26:in `run_data_miner!'
  from /Users/seamusabshere/code/data_miner/lib/data_miner.rb:82:in `block (2 levels) in start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner.rb:81:in `map'
  from /Users/seamusabshere/code/data_miner/lib/data_miner.rb:81:in `block in start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner/script.rb:11:in `uniq'
  from /Users/seamusabshere/code/data_miner/lib/data_miner.rb:80:in `start'
  from /Users/seamusabshere/code/data_miner/lib/data_miner.rb:128:in `run'
  from /Users/seamusabshere/code/data_miner/test/test_earth_tap.rb:10:in `<top (required)>'
```

**Comment by searls** [comment]
FWIW, this is still an issue. I'm relying on PG merge and have a partial upsert routine and because it doesn't update every nullable column it will fail with `=> #<PG::NotNullViolation: ERROR:  null value in column`
