### ISSUE TITLE
Cannot update table within a schema (Postgres)

### ISSUE THREAD

**Issue by zakcrawford** [seamusabshere/upsert#53]
## Cannot update table within a schema (Postgres)

Here is where the table name is being interpolated:
https://github.com/seamusabshere/upsert/blob/master/lib/upsert/column_definition/postgresql.rb#L12

Here is how it can be fixed

```
If the parameter is an Array, then all it's values are separately quoted
and then joined by a “.” character.This can be used for identifiers in 
the form “schema”.“table”.“column” .
```

The line above needs to be changed to pass an array of table_name, and schema. Not sure what the best way to extract the schema from the table_name string, you could also just pass the string through verbatim with simple quote escaping as an easy fix.

```
[23] pry(#<Datawarehouse::UpsertWorker>)> active_record.table_name= 'dialer.leads'
=> "dialer.leads"
[24] pry(#<Datawarehouse::UpsertWorker>)> active_record.upsert(update_by, attributes)
D, [2015-07-10T17:06:07.629033 #57624] DEBUG -- : [upsert] SELECT a.attname AS name, format_type(a.atttypid, a.atttypmod) AS sql_type, d.adsrc AS default
FROM pg_attribute a LEFT JOIN pg_attrdef d
  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attrelid = '"dialer.leads"'::regclass
AND a.attnum > 0 AND NOT a.attisdropped

PG::UndefinedTable: ERROR:  relation "dialer.leads" does not exist
LINE 4: WHERE a.attrelid = '"dialer.leads"'::regclass
                           ^
from /Users/zak/.rvm/gems/ruby-2.2.0/gems/upsert-2.1.0/lib/upsert/connection/PG_Connection.rb:13:in `exec'

# And with quoted table names
[25] pry(#<Datawarehouse::UpsertWorker>)> active_record.table_name= '"dialer"."leads"'
=> "\"dialer\".\"leads\""
[26] pry(#<Datawarehouse::UpsertWorker>)> active_record.upsert(update_by, attributes)
D, [2015-07-10T17:07:14.698160 #57624] DEBUG -- : [upsert] SELECT a.attname AS name, format_type(a.atttypid, a.atttypmod) AS sql_type, d.adsrc AS default
FROM pg_attribute a LEFT JOIN pg_attrdef d
  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attrelid = '"""dialer"".""leads"""'::regclass
AND a.attnum > 0 AND NOT a.attisdropped

PG::UndefinedTable: ERROR:  relation ""dialer"."leads"" does not exist
LINE 4: WHERE a.attrelid = '"""dialer"".""leads"""'::regclass
                           ^
from /Users/zak/.rvm/gems/ruby-2.2.0/gems/upsert-2.1.0/lib/upsert/connection/PG_Connection.rb:13:in `exec'
```

**Comment by pnomolos** [comment]
@seamusabshere What's your thoughts on this one?  I'm going to need it myself so it'll be next on my list :)

**Comment by pnomolos** [comment]
This should now be fixed as well.
