### ISSUE TITLE
On mysql trying to write to an undefined field fails confusingly

### ISSUE THREAD

**Issue by ihough** [seamusabshere/upsert#9]
In a `data_miner` block `store 'foo', :units => :bar` produces the following error if the table does not have a  `foo_units` column.

```
 Failure/Error: Unable to find matching line from backtrace
 Mysql2::Error:
   Incorrect number of arguments for PROCEDURE test_earth.upsert_recs_2009_responses_SEL_id_SET_computer_2_idl3386076219; expected 82, got 83
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/upsert-1.0.2/lib/upsert/connection/Mysql2_Client.rb:7:in `query'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/upsert-1.0.2/lib/upsert/connection/Mysql2_Client.rb:7:in `execute'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/upsert-1.0.2/lib/upsert/merge_function/Mysql2_Client.rb:21:in `execute'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/upsert-1.0.2/lib/upsert/merge_function.rb:11:in `execute'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/upsert-1.0.2/lib/upsert.rb:145:in `row'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/step/import.rb:95:in `block (2 levels) in start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/remote_table-2.1.0/lib/remote_table.rb:435:in `block (2 levels) in each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/remote_table-2.1.0/lib/remote_table.rb:424:in `each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/remote_table-2.1.0/lib/remote_table.rb:424:in `block in each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/remote_table-2.1.0/lib/remote_table/delimited.rb:66:in `block in _each'
 # /Users/ian/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/csv.rb:1768:in `each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/remote_table-2.1.0/lib/remote_table/delimited.rb:35:in `_each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/remote_table-2.1.0/lib/remote_table.rb:423:in `each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/step/import.rb:89:in `block in start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/upsert-1.0.2/lib/upsert.rb:73:in `batch'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/step/import.rb:88:in `start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/script.rb:227:in `block (2 levels) in start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/script.rb:226:in `each'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/script.rb:226:in `block in start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/run.rb:93:in `block in start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/run.rb:92:in `catch'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/run.rb:92:in `start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/script.rb:225:in `start'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/data_miner-2.4.1/lib/data_miner/active_record_class_methods.rb:26:in `run_data_miner!'
 # /Users/ian/code/earth/spec/spec_helper.rb:36:in `block (2 levels) in <top (required)>'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:23:in `instance_eval'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:23:in `run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:106:in `run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/hooks.rb:424:in `run_hook'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:312:in `run_before_all_hooks'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:359:in `run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `map'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block in run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/reporter.rb:34:in `report'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:25:in `run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
 # /Users/ian/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
```

**Comment by pnomolos** [comment]
Closing this, as it was fixed via commit f51c9eab
